/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "main.h"


TIM_HandleTypeDef TIM6Handle;
TIM_HandleTypeDef TIM1Handle;
GPIO_HandleTypeDef EXTIHandle;


void GPIO_TestInit(void);


int main(void)
{
	Delay_ms(1000);

	// 1. System Clock configuration to 72MHz
	SystemClock_Config(SYSCLK_FREQ_72MHZ);

	// 2. Clear All members of Handle structures to 0
	memset(&TIM6Handle, 0, sizeof(TIM6Handle));
	memset(&TIM1Handle, 0, sizeof(TIM1Handle));
	memset(&EXTIHandle, 0, sizeof(EXTIHandle));

	// 3. Initialize peripherals
	GPIO_BLDC_Init();			// GPIO init for U/V/W
	EXTI_Init(&EXTIHandle);		// EXTI init for Interrupt triggered by Hallphase change
	TIM6_Init(&TIM6Handle);		// TIM6 init for 1ms period of time base
	TIM1_Init(&TIM1Handle);		// TIM1 init for PWM generation to drive BLDC motor

	// 4. Charge Bootstrap Capacitor
	BLDC_BootstrapCap_Charge();

	// 5. Start PWM for UB, VB, WB
	TIM_PWM_Start(&TIM1Handle, TIM_CHANNEL_1);			// Start PWM for UB
	TIM_PWM_Start(&TIM1Handle, TIM_CHANNEL_2);			// Start PWM for VB
	TIM_PWM_Start(&TIM1Handle, TIM_CHANNEL_3);			// Start PWM for WB

	// 6. Disable All PWM channels
	TIM_DISABLE_CHANNEL(&TIM1Handle, TIM_CHANNEL_1);
	TIM_DISABLE_CHANNEL(&TIM1Handle, TIM_CHANNEL_2);
	TIM_DISABLE_CHANNEL(&TIM1Handle, TIM_CHANNEL_3);

	// 7. Set PWM duty to 10%
	TIM_SET_COMPARE(&TIM1Handle, TIM_CHANNEL_1, 80);	// 80% duty
	TIM_SET_COMPARE(&TIM1Handle, TIM_CHANNEL_2, 80);	// 80% duty
	TIM_SET_COMPARE(&TIM1Handle, TIM_CHANNEL_3, 80);	// 80% duty

	Delay_ms(1000);

	GPIO_TestInit();

	while(1)
	{

	}
}


void GPIO_TestInit(void)
{
	GPIO_InitTypeDef GPIOInit;

	memset(&GPIOInit, 0, sizeof(GPIOInit));

	GPIOInit.Pin = GPIO_PIN_1;
	GPIOInit.Mode = GPIO_MODE_OUTPUT_PP;
	GPIOInit.Pull = GPIO_NOPULL;
	GPIOInit.Speed = GPIO_SPEED_FREQ_MEDIUM;
	GPIO_Init(GPIOA, &GPIOInit);
}
