/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "main.h"


TIM_HandleTypeDef TIM6Handle;
TIM_HandleTypeDef TIM1Handle;

int main(void)
{
	SystemClock_Config(SYSCLK_FREQ_72MHZ);

	GPIOTest_Init();

	memset(&TIM6Handle, 0, sizeof(TIM6Handle));
	memset(&TIM1Handle, 0, sizeof(TIM1Handle));

	TIM6_Init(&TIM6Handle);
	TIM1_Init(&TIM1Handle);

	TIM_PWM_Start(&TIM1Handle, TIM_CHANNEL_1);
	TIM_PWM_Start(&TIM1Handle, TIM_CHANNEL_2);
	TIM_PWM_Start(&TIM1Handle, TIM_CHANNEL_3);
	TIM_PWM_Start(&TIM1Handle, TIM_CHANNEL_4);

	while(1)
	{
		for(int i=0; i<=10; i++)
		{
			TIM_SET_COMPARE(&TIM1Handle, TIM_CHANNEL_1, (uint16_t)i);
			Delay_ms(100);
		}
	}
}
