/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "main.h"


TIM_HandleTypeDef TIM6Handle;


int main(void)
{
	SystemClock_Config(SYSCLK_FREQ_72MHZ);

	GPIOTest_Init();

	memset(&TIM6Handle, 0, sizeof(TIM6Handle));

	TIM6_Init(&TIM6Handle);

	NVIC_IRQConfig(IRQ_NO_TIM6, NVIC_PRIOR_15, ENABLE);
	TIM_ENABLE_IT(&TIM6Handle, TIM_IT_UPDATE);
	TIM_ENABLE_COUNTER(&TIM6Handle);


	while(1)
	{

	}
}
